{"uuid": "c35f92a7-8f06-42d5-b60d-1a06063d0200", "children": ["c7270c1f-9bf3-46e0-9bc5-094cc106dfad"], "befores": [{"name": "setup_browser", "status": "passed", "start": 1667146414625, "stop": 1667146424972}], "afters": [{"name": "setup_browser::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot activate web view\n  (Session info: chrome=100.0.4896.60)\nStacktrace:\n#0 0x56408f8e0013 <unknown>\n#1 0x56408f642a08 <unknown>\n#2 0x56408f632ed3 <unknown>\n#3 0x56408f6264b9 <unknown>\n#4 0x56408f6b5f19 <unknown>\n#5 0x56408f696932 <unknown>\n#6 0x56408f6a9b94 <unknown>\n#7 0x56408f696823 <unknown>\n#8 0x56408f66c08a <unknown>\n#9 0x56408f66d1e5 <unknown>\n#10 0x56408f90de5d <unknown>\n#11 0x56408f927061 <unknown>\n#12 0x56408f90fbb5 <unknown>\n#13 0x56408f927e08 <unknown>\n#14 0x56408f9032f0 <unknown>\n#15 0x56408f943988 <unknown>\n#16 0x56408f943b08 <unknown>\n#17 0x56408f95d5dd <unknown>\n#18 0x7f51cb5dc609 <unknown>\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 209, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 909, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/a11/Documents/qa.guru/final/test/conftest.py\", line 61, in setup_browser\n    attach.add_screenshot(browser)\n  File \"/Users/a11/Documents/qa.guru/qa_guru_python_lesson_final/utils/attach.py\", line 8, in add_screenshot\n    png = browser.driver.get_screenshot_as_png()\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 962, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 974, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 428, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "attachments": [{"name": "page_source", "source": "8a81ecca-c2c9-4c9f-9d5d-6f0c48a69cb1-attachment.html", "type": "text/html"}], "start": 1667146432843, "stop": 1667146433302}], "start": 1667146414625, "stop": 1667146433302}